# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "vivid_vervet"
    config.vm.network "forwarded_port", guest: 3000, host: 3000 

    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
end
